namespace: community
name: mongodb
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  community.general: '>=0.1.1'
repository: git@github.com:ansible-collections/mongodb.git
documentation: https://github.com/ansible-collections/mongodb/tree/master/docs
homepage: https://github.com/ansible-collections/mongodb
issues: https://github.com/ansible-collections/mongodb/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
