---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: almalinux_8
    image: almalinux:8
    command: /sbin/init
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "mongod"
    network_mode: "mongod"
  - name: ubuntu_18
    image: ubuntu:18.04
    command: /sbin/init
    privileged: True
    networks:
      - name: "mongod"
    network_mode: "mongod"
  - name: ubuntu_22
    image: ubuntu:22.04
    command: /sbin/init
    privileged: True
    networks:
      - name: "mongod"
    network_mode: "mongod"
  - name: debian_bullseye
    image: debian:bullseye
    command: /sbin/init
    privileged: True
    networks:
      - name: "mongod"
    network_mode: "mongod"
  - name: fedora
    image: fedora:37
    command: /sbin/init
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
    networks:
      - name: "mongod"
    network_mode: "mongod"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  inventory:
    host_vars:
      debian_bullseye:
        ansible_python_interpreter: /usr/bin/python3
      fedora:  # suitable for fedora 37
        redhat:
          yum_baseurl: "https://repo.mongodb.org/yum/redhat/9/mongodb-org/{{ mongodb_version }}/x86_64/"
          rpm_key_key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
          yum_gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
          yum_gpgcheck: true
          yum_description: "Official MongoDB {{ mongodb_version }} yum repo"
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
