---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: centos_7
    hostname: centos_7
    image: centos:7
    command: /sbin/init
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "mymongo"
    network_mode: "mymongo"
  - name: ubuntu_18
    hostname: ubuntu_18
    image: ubuntu:18.04
    command: /sbin/init
    privileged: True
    networks:
      - name: "mymongo"
    network_mode: "mymongo"
  - name: debian_buster
    hostname: debian_buster
    image: debian:buster
    command: /sbin/init
    privileged: True
    networks:
      - name: "mymongo"
    network_mode: "mymongo"
  - name: debian_bullseye
    hostname: debian_bullseye
    image: debian:bullseye
    command: /sbin/init
    privileged: True
    networks:
      - name: "mymongo"
    network_mode: "mymongo"
  - name: amazonlinux
    hostname: amazonlinux
    image: amazonlinux:2
    command: /sbin/init
    privileged: True  
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: "mymongo"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  inventory:
    host_vars:
      debian_bullseye:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
