---
# tasks file for mongodb_firewalld
- name: Include vars for os family
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Ensure firewalld package is installed
  package:
    name: "{{ firewalld_packages }}"
    state: present

- name: Ensure firewalld service is started
  service:
    name: firewalld
    state: started
    enabled: yes
