---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  #- name: centos_7  Failed to load nf_conntrack module: modprobe: ERROR:...ack
  #  image: centos:7
  #  command: /sbin/init
  #  privileged: True
  - name: ubuntu_16
    hostname: ubuntu_16
    image: ubuntu:16.04
    command: /sbin/init
    privileged: True
    networks:
      - name: mongos
    network_mode: mongos
    dns_servers:
      - 127.0.0.11
      - 8.8.8.8
  - name: ubuntu_18
    hostname: ubuntu_18
    image: ubuntu:18.04
    command: /sbin/init
    privileged: True
    networks:
      - name: mongos
    network_mode: mongos
    dns_servers:
      - 127.0.0.11
      - 8.8.8.8
  #- name: debian_buster ERROR: Failed to load nf_conntrack module
  #  image: debian:buster
  #  command: /sbin/init
  #  privileged: True
  - name: debian_stretch
    hostname: debian_stretch
    image: debian:stretch
    command: /sbin/init
    privileged: True
    networks:
      - name: mongos
    network_mode: mongos
    dns_servers:
      - 127.0.0.11
      - 8.8.8.8
  - name: config1
    hostname: config1
    image: ubuntu:16.04
    command: /sbin/init
    privileged: True
    networks:
      - name: mongos
    network_mode: mongos
    dns_servers:
      - 127.0.0.11
      - 8.8.8.8
  - name: config2
    hostname: config2
    image: ubuntu:16.04
    command: /sbin/init
    privileged: True
    networks:
      - name: mongos
    network_mode: mongos
    dns_servers:
      - 127.0.0.11
      - 8.8.8.8
  - name: config3
    hostname: config3
    image: ubuntu:16.04
    command: /sbin/init
    privileged: True
    networks:
      - name: mongos
    network_mode: mongos
    dns_servers:
      - 127.0.0.11
      - 8.8.8.8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
