---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  #- name: centos_7  Failed to load nf_conntrack module: modprobe: ERROR:...ack
  #  image: centos:7
  #  command: /sbin/init
  #  privileged: True
  - name: ubuntu_16
    image: ubuntu:16.04
    command: /sbin/init
    privileged: True
    networks:
      - name: "mymongos"
    network_mode: "mymongos"
  - name: ubuntu_18
    image: ubuntu:18.04
    command: /sbin/init
    privileged: True
    networks:
      - name: "mymongos"
    network_mode: "mymongos"
  #- name: debian_buster ERROR: Failed to load nf_conntrack module
  #  image: debian:buster
  #  command: /sbin/init
  #  privileged: True
  - name: debian_stretch
    image: debian:stretch
    command: /sbin/init
    privileged: True
    networks:
      - name: "mymongos"
    network_mode: "mymongos"
  - name: config1
    image: ubuntu:16.04
    command: /sbin/init
    privileged: True
    networks:
      - name: "mymongos"
    network_mode: "mymongos"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
