---
- name: Converge
  hosts: all
  become: yes

  roles:
    - role: mongodb_firewalld
    - role: mongodb_repository
    - { role: mongodb_mongos, when: "'config' not in ansible_hostname" }
    - { role: mongodb_install, when: "'config' in ansible_hostname" }
    - { role: mongodb_config, when: "'config' in ansible_hostname" }

  tasks:

    - name: Install python stuff
      package:
        name: ["python-setuptools", "python-pip"]
      when: ansible_hostname == "config1"

    - name: Install pymongo
      pip:
        name: pymongo
      when: ansible_hostname == "config1"

    - name: Init config server replicaset
      mongodb_replicaset:
        login_host: localhost
        login_port: 27019
        replica_set: cfg
        members:
          - config1:27019
          #- config2:27019
          #- config3:27019
      when: ansible_hostname == "config1"
