---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      line-length: disable
platforms:
  - name: centos_7
    image: centos:7
  - name: amazonlinux
    image: amazonlinux:2
  - name: ubuntu_18
    image: ubuntu:18.04
  - name: debian_buster
    image: debian:buster
  - name: debian_bullseye
    image: debian:bullseye
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  inventory:
    host_vars:
      debian_bullseye:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      ignore: 'E501'
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
