# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

# For CentOS 8 Only
RUN if [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python2 sudo python2-devel python*-dnf bash iproute && dnf clean all; \
    else exit 1 \
    fi
