---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: amazon2023
    image: geerlingguy/docker-amazonlinux2023-ansible
  - name: debian11
    image: quay.io/aminvakil/debian11-systemd
  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
  - name: almalinux9
    image: almalinux:9.4
  - name: rockylinux9
    image: rockylinux:9.3
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
