---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: amazon2023
    image: geerlingguy/docker-amazonlinux2023-ansible
    privileged: true
  - name: debian12
    image: quay.io/aminvakil/debian12-systemd
    privileged: true
  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
    privileged: true
  - name: almalinux9
    image: mullholland/docker-almalinux-systemd:9
    privileged: true
  - name: rockylinux9
    image: geerlingguy/docker-rockylinux9-ansible
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
