name: TEST
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/community/mongodb
    outputs:
      matrix: ${{ steps.json-list.outputs.modules-to-test }}

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/mongodb

      - name: Generate module list
        run: |
          find tests/integration/targets -type d -maxdepth 1 -not -name 'setup*' | cut -d '/' -f4 | sort | awk NF > int_test_modules.txt

      - name: Generate json doc from module list
        run: |
          cat int_test_modules.txt | jq -sR '{"modules": split("\n")[:-1] }' > int_test_modules.json

      - name: Format to json list
        id: json-list
        run: |
          output=$(python -c 'import json;print(json.load(open("int_test_modules.json")))')
          echo "::set-output name=modules-to-test::$output"
          echo "$output"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.job1.outputs.matrix) }}

    steps:

      - name: Iterate over items
        run: |
          echo ${{ matrix.module }}
